### ISSUE TITLE
Existing issues after review (missing specs, autogenerate params for create, update, and search)

### ISSUE THREAD

**Issue by dukenguyenxyz** [PlaceOS/crystal-client#13]
# Missing specs

The following list documents classes followed by their methods for the missing spec

Cluster
- [ ] Search
- [ ] Fetch
- [ ] Destroy

Domains
- [ ] Update

Metadata
- [ ] Children

Modules
- [ ] Ping
- [ ] Execute

Repositories
- [ ] Branches
- [ ] Details

Root
- [ ] Signal
- [ ] Version
- [ ] Root

Settings
- [ ] History

System Triggers
- [ ] Create
- [ ] Update

Systems
- [ ] Control

Triggers
- [ ] Instances

Users
- [ ] Resource_token

Zones
- [ ] Execute

Auths
- [ ] Search
- [ ] Create
- [ ] Update

Brokers (missing methods as well as specs)
- [ ] Search
- [ ] Fetch
- [ ] Create
- [ ] Update
- [ ] Destroy

# Additional Improvements

* [ ] Autogenerate create and update method params from model
* [ ] Autogenerate search fields for search method params from elastic/model

**Comment by dukenguyenxyz** [comment]
@caspiano

**Comment by jeremyw24** [comment]
Closing in favour of using OpenAPI Generation.
